### ISSUE TITLE
Add an applicable open source license

### ISSUE THREAD

**Issue by Xaeroxe** [NZXTCorp/enunion#6]
Hi, it's me again. I'm no longer employed by NZXT but I find myself back in this Rust/Node ecosystem again.

It's nice to have the repo public, but I can't actually make use of this software without an explicit license granting me permission. Consider adding a permissive license such as MIT or BSD 3 clause. It'd be much appreciated.

**Comment by seritools** [comment]
Asking around to see if we can just MIT+Apache2 it
